config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'transactions#index'

  resources :transactions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :transaction_type
  belongs_to :user
end

app/models/transaction_type.rb
class TransactionType < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = {}
    @total_balance = 0
    @store_balance = {}

    Transaction.where(user_id: current_user.id).order(:store, :id).each do |transaction|
      attributes = transaction.attributes
      
      unless @transactions[attributes['store']]
        @store_balance[attributes['store']] = 0
        @transactions[attributes['store']] = []
      end

      attributes['transaction_type'] = transaction.transaction_type
      
      if transaction.transaction_type.signal === "+"
        @store_balance[attributes['store']] += attributes['value']
        @total_balance += attributes['value']
      else
        @store_balance[attributes['store']] -= attributes['value']
        @total_balance -= attributes['value']
      end

      attributes['balance'] = @store_balance[attributes['store']]

      puts "Atributos: #{attributes}"
      @transactions[transaction.store] << attributes
    end
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # POST /transactions
  # POST /transactions.json
  def create
    file = params[:arquivo].read

    errors = []

    file.each_line.with_index do |line, index|
      begin
        fields = {}

        transaction_type = TransactionType.find_by code: line[0]

        raise "Tipo de transação não encontrada" unless transaction_type

        fields['transaction_type'] = transaction_type
        fields['date'] = "#{line[1..8]}#{line[42..47]}"
        fields['value'] = line[9..18]
        fields['cpf'] = line[19..29]
        fields['card'] = line[30..41]
        fields['store_owner'] = line[48..61].strip
        fields['store'] = line[62..80].strip.delete("\n")
        fields['user_id'] = current_user.id

        @transaction = Transaction.create fields
      rescue Exception => e
        errors << { line: index+1, message: e.message}
      end
    end

    if errors.empty?
      @message_class = 'success'
      @notice_message = 'Arquivo importado com sucesso!'
    else 
      @message_class = 'warning'
      @notice_message = "Arquivo importado com os seguintes erros:<ul>"
        
      errors.each do |error|
        @notice_message += "<li>Linha: #{error[:line]}, Erro: #{error[:message]}</li>"
      end

       @notice_message += "</ul>"
    end

    flash[:notice] = @notice_message
    flash[:notice_class] = @message_class

    redirect_to transactions_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:arquivo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <p class="pull-right">Olá <%= current_user.email %> - <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1>Relatório de Transações Financeiras</h1>
</div>

<% if flash[:notice] %>
  <div class="alert alert-<%= flash[:notice_class] %>" role="alert"><%= flash[:notice].html_safe %></div>
<%- end %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Data e Hora</th>
      <th>Valor</th>
      <th>CPF</th>
      <th>Cartão</th>
      <th>Dono da Loja</th>
      <th>Nome da Loja</th>
      <th>Saldo</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |store,transactions| %>
      <tr>
        <td colspan="8" class="title"><%= store %></td>
      </tr>
      <% transactions.each do |transaction| %>
        <tr>
          <td><%= transaction['transaction_type']&.code %></td>
          <td><%= transaction['date'].strftime("%d/%m/%Y %H:%M:%S") %></td>
          <td><%= number_to_currency transaction['value'], unit: "R$ ", separator: ",", delimiter: "." %></td>
          <td><%= transaction['cpf'] %></td>
          <td><%= transaction['card'] %></td>
          <td><%= transaction['store_owner'] %></td>
          <td><%= transaction['store'] %></td>
          <td><%= number_to_currency transaction['balance'], unit: "R$ ", separator: ",", delimiter: "." %></td>
        </tr>
      <% end %>

      <tr class="sum">
        <td colspan="7">SALDO (<%= store %>):</td>
        <td align="left"><%= number_to_currency @store_balance[store], unit: "R$ ", separator: ",", delimiter: "." %></td>
      </tr>
    <% end %>

    <% unless @transactions.empty? %>
      <tr class="sum">
        <td colspan="7">SALDO GERAL:</td>
        <td align="left"><%= number_to_currency @total_balance, unit: "R$ ", separator: ",", delimiter: "." %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<%= link_to "Importar Transações", new_transaction_path, :class => 'btn btn-primary' %>

app/views/transactions/new.html.erb
<%- model_class = Transaction -%>
<div class="page-header">
  <h1>Importar Arquivo de Transações Financeiras</h1>
</div>

<%= form_tag "/transactions", :class => "form-horizontal transaction", multipart: true do %>

  <% if @transaction.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @transaction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= label_tag "Arquivo" %>
    <div class="col-lg-6">
      <%= file_field_tag :arquivo, :class => 'form-control', required: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-6">
      <%= submit_tag "Importar", :class => "btn btn-primary" %>
      <%= link_to "Voltar", transactions_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>